### ISSUE TITLE
touch ripple animation when touch occurs?  

### ISSUE THREAD

**Issue by callagga** [nateshmbhat/touchable#14]
How would one get a touch ripple effect on a canvas here, to indicate to the user the touch did occur?   (noting that in some apps the touch may only 'do something' if they touch the appropriate point, but still want to highlight there touch in general whether over a touchable object or not - i.e. for any touch on the canvas)

An effect such as InkRipple (https://api.flutter.dev/flutter/material/InkRipple-class.html) however not sure it this works on a canvas?

**Comment by nateshmbhat** [comment]
you have to paint it manually in your application
