### ISSUE TITLE
How to change state of shapes using touchable?

### ISSUE THREAD

**Issue by ameeee** [nateshmbhat/touchable#16]
```
class MyPainter extends CustomPainter { 

  @override
  void paint(Canvas canvas, Size size) {
var myCanvas = TouchyCanvas(context,canvas);
  myCanvas.drawRect( rect , paint , onPanDown: (tapDetail){
   print("rectangle touch");
  print(rect.width);
paint.color=Colors.black;

  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }

}
```

Changing the color by paint.color doesn't change the color of the rectangle... how would the state change ? it's only printing stuff.

Thank you for this library.

**Comment by markovicdenis** [comment]
You would probably have to save the color outside of the painter in a stateful widget and pass it down. You'd also have to pass down the callback function that changes the color and calls "setState" function and repaints the painter.

**Comment by nateshmbhat** [comment]
You can see the example screens code
