### ISSUE TITLE
[flutter-bug] Doesn't recognise touch events when custompaint object is part of a stack

### ISSUE THREAD

**Issue by greencow555** [nateshmbhat/touchable#2]
```
Stack(
        alignment: Alignment.center,
        children: <Widget>[
          OtherWidgetContainer(),
          CanvasTouchDetector(
            builder: (context) => CustomPaint(
              painter: SquibCircle(context), //this does nothing. Remove the stack and it works great. 
            ),
          ),
        ],
      ),
```

**Comment by nateshmbhat** [comment]
are you sure you are using the Stack properly ?

**Comment by Albert-Jan** [comment]
Hi! I'm facing exactly the same issue! Any solutions for this?

**Comment by nateshmbhat** [comment]
can you check touchable version 0.1.7 ? 

feel free to reopen this issue if that too doesn't work.

**Comment by Albert-Jan** [comment]
Thank you very for picking this up so quickly, but unfortunately, that did not work.
I modified your example code to display the issue.

`import 'package:flutter/material.dart';
import 'package:touchable/touchable.dart';

class ExperimentPainterTouch extends StatefulWidget {
  ExperimentPainterTouch({Key key}) : super(key: key);

  @override
  _ExperimentPainterTouchState createState() => _ExperimentPainterTouchState();
}

class _ExperimentPainterTouchState extends State<ExperimentPainterTouch> {
  @override
  Widget build(BuildContext context) {
    return Flex(
      direction: Axis.horizontal,
      children: <Widget>[
        Expanded(
          child: Stack(
            children: <Widget>[
              CanvasTouchDetector(
                builder: (context) {
                  return CustomPaint(
                    painter: MyPainter(context),
                  );
                },
              )
            ],
          ),
        )
      ],
    );
  }
}

class MyPainter extends CustomPainter {
  final BuildContext context;

  MyPainter(this.context); // context from CanvasTouchDetector

  @override
  void paint(Canvas canvas, Size size) {
    var myCanvas = TouchyCanvas(context, canvas);

    myCanvas.drawCircle(Offset(100, 100), 60, Paint()..color = Colors.orange, onTapDown: (tapdetail) {
      print('orange Circle touched');
    }, onPanDown: (tapdetail) {
      print('orange circle swiped');
    });

    myCanvas.drawLine(
        Offset(0, 0),
        Offset(size.width - 100, size.height - 100),
        Paint()
          ..color = Colors.black
          ..strokeWidth = 50, onPanUpdate: (detail) {
      print('Black line Swiped'); //do cooler things here. Probably change app state or animate
    });
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return false;
  }
}
`

**Comment by nateshmbhat** [comment]
can you try wrapping the `CanvasTouchDetector` inside SizedBox.expand ? 

```
SizedBox.expand(
child: <your child> 
);
```

**Comment by Albert-Jan** [comment]
I did and it worked, unfortunately, the rest of my application broke down after doing this. My panning around didn't work as expected anymore. I Will experiment with this more, thanks for the help! Currently working on a native mind mapping system, but it is harder to build than I anticipated. Will keep you posted what fixed my issue to use this library together with a custom zooming and panning parent widget.

**Comment by nateshmbhat** [comment]
https://stackoverflow.com/questions/52965799/flutter-gesturedetector-not-working-with-containers-in-stack

Do check out this SO post too.
I still think the issue is something related to how it's being used inside the stack since canvas touch detector is nothing but a gesture detector.

**Comment by Albert-Jan** [comment]
The weird aspect of this is that a gesture detector which is in the same stack as the canvas is still working as expected

**Comment by Albert-Jan** [comment]
Scaffold -> LayoutBuilder -> Container -> GestureDector -> Stack {
    Positioned -> Container -> Stack {
        Positioned -> CanvasTouchDetector -> Custom Painter
        Positioned -> ... a lot of other widgets which are displayed on top
    }
}

**Comment by nateshmbhat** [comment]
Can u provide a clearer example with code snippet. The above representation is not clear.

**Comment by Albert-Jan** [comment]
Below is my full tree, when I wrap the CanvasTouchDetector in SizedBox.expand(), it results in the onPan gesture detector not being triggered, but the CanvasTouchDetector is triggered. When I leave SizedBox.expand() out of the code, the onPan gets triggered but not the canvas. 

```
Scaffold(
      appBar: AppBar(
        title: Text('Mapped test'),
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          return Container(
            color: Colors.white,
            width: MediaQuery.of(context).size.width,
            height: constraints.maxHeight,
            child: GestureDetector(
              behavior: HitTestBehavior.translucent,
              onPanUpdate: _handlePanUpdate,
              child: Stack(
                children: <Widget>[
                  Positioned(
                      top: top,
                      left: left,
                      width: 6000 * ratio,
                      height: 6000 * ratio,
                      child: Container(
                          decoration: BoxDecoration(
                            color: Colors.grey[50],
                            border: Border.all(
                              color: Color(0xff1a73e8),
                            ),
                            borderRadius: BorderRadius.circular(10.0),
                          ),
                          child: Stack(
                            children: <Widget>[
                              CanvasTouchDetector(
                                  builder: (context) => CustomPaint(
                                        painter: ArrowPainter(context, ratio, left,
                                            top, dragItems, lines),
                                      )),
                              Stack(
                                children: allItems,
                              ),
                            ],
                          ))),
                ],
              ),
            ),
          );
        },
      ),
);
```

**Comment by nateshmbhat** [comment]
Can u try by removing all positioned widget stuff and just having a simple stack and the canvas detector?

**Comment by Albert-Jan** [comment]
I figured it out! Wow. That was intense. Thank you very much! It turned out that the onPan gesture was hijacked by CanvasTouchDetector. So it worked all the time but it just wasn't being triggered. I went into the source of Touchable and removed the onPan gesture. Now everything is working as expected. Thank you very much for investing this much time in the issue.

**Comment by nateshmbhat** [comment]
That's great man 😁😁👌

So is the bug in the touchable library ?

Can u describe exactly what changes u did so that others facing the same issue can try it ?

What do you mean when u say "onPan is hijacked by canvas touch detector"
 but it was working fine" ?

**Comment by Albert-Jan** [comment]
When you have two gesture detectors in the same widget tree, only one 'method' will get called. So if GD1 only has the onPan and GD2 only has the onTap, they will work both as there is no interference. But Touchable initializes every 'method' that can be detected, onTapDown, onTapUp, onLongPressDown, etc... and so it also activates the onPan method. This was however not needed in my case in the Touchable canvas but on an upper gesture detector, so it got triggered by Touchable instead of GD1. By removing the onPan method from the library there was no interference between both gesture detectors. Now all gestures are being detected. 

Not sure if this is something that should be an issue for Touchable, but the fact it uses every method and initializes it, resulted in my issue.
 
The following SO issue explained it to me quite nicely and solved my issue. 

> The issue was the following: The onHorizontalDrag and onVerticalDrag gestures will always come before onPan and will prevent onPan from being called (even if the GestureDetector listening to the onHorizontalDrag event is behind the one listening to the onPan event). Adding any listener to onHorizontalDrag on the small container (even just onHorizontalDragCancel) will make the small container get and consume the event (which means the big one under will not receive it).

https://stackoverflow.com/questions/50764553/have-2-gesture-detectors-with-same-gesture-on-the-same-page-in-flutter

**Comment by nateshmbhat** [comment]
Yes , this is not an issue with Touchable actually. 

it's how Flutter handles the gesture detectors. I thought using Translucent hit test behaviour should have called the call back methods of both GDs.
