### ISSUE TITLE
Unable to get detect onTapDown and onPanDown events on TouchyCanvas

### ISSUE THREAD

**Issue by chetanbanandur** [nateshmbhat/touchable#20]
The sample project is not detecting any gesture call back.

**Comment by nateshmbhat** [comment]
I have looked into this. The example listed on touchable is broken right now. Will put up a more complete example by the end of #21 

The issue is related to some incompatibilities in Flutter version 2

**Comment by nateshmbhat** [comment]
Turns out the issue was in touchable code base itself. Am fixing it now. Will publish today night.

**Comment by nateshmbhat** [comment]
Published version 0.2.1
