### ISSUE TITLE
Add support for Null Safety

### ISSUE THREAD

**Issue by RegisSaffi** [nateshmbhat/touchable#21]
This is not a bug or issue, but i wanted to upgrade my current application to Flutter 2, but detected that Touchable does not have support for null safety.

It could be good if this package upgraded to null safety in case someone want to upgrade to Flutter 2

**Comment by nateshmbhat** [comment]
Yes will work on it today itself.

**Comment by nateshmbhat** [comment]
Adding null safety support his week 👍🏻

**Comment by RegisSaffi** [comment]
This will be awesome 😎

**Comment by nateshmbhat** [comment]
this is the branch if anyone wants it right now : https://github.com/nateshmbhat/touchable/tree/null-safety-migration

**Comment by nateshmbhat** [comment]
Published the package here : https://pub.dev/packages/touchable/versions/1.0.0-prerelease

Please test and let me know if you guys find any issues. I will publish it was a proper release version then 👍🏻

**Comment by RegisSaffi** [comment]
Thanks for pre-release, let me test it and i will confirm

**Comment by nateshmbhat** [comment]
cool 👍🏻

**Comment by nateshmbhat** [comment]
@RegisSaffi were you able to test it ?

**Comment by whiplashoo** [comment]
Using it in production (with a few lines commented out) for the past few days, no issues found.

**Comment by nateshmbhat** [comment]
@whiplashoo please mention what lines did you comment and why

**Comment by whiplashoo** [comment]
@nateshmbhat Should have worded it out better: I am using it with some of the gesture listeners (onForcePress, onPan, onSecondaryTap) deactivated for my particular use case. This has nothing to do with the null safety update; everything works as expected.

**Comment by nateshmbhat** [comment]
cool

**Comment by RegisSaffi** [comment]
Hey, 
Sorry for late reply but as of now I am not having any issue with the pre-release version.

**Comment by nateshmbhat** [comment]
Released touchable null safe version 1.0.0 ✌🏻
