### ISSUE TITLE
How to draw text on the TouchyCanvas?

### ISSUE THREAD

**Issue by S-Man42** [nateshmbhat/touchable#25]
Is there a way to use a `TextPainter `on the canvas? Or is there a way to access the normal `Canvas `member to do this?

**Comment by randspace0** [comment]
Ah yes, closing issue without any context. Mind to share your solution?

**Comment by S-Man42** [comment]
Thanks for your very kind, non-offending request. That's the way making people help you with pleasure... 🙄

Well, for me, it works to take the Canvas instance, which is used to create a TouchyCanvas, directly to draw some text on it. So, TouchyCanvas is used for drawing touchy Rects and the normal Canvas is used to draw text. Don't know if you could call it a solution.

https://github.com/S-Man42/GCWizard/blob/9c5e2d916fe2ac1c48e21659f23a718fc73e8145/lib/widgets/tools/games/sudoku/sudoku_board.dart#L110
