### ISSUE TITLE
Panning and scaling inside an InteractiveViewer

### ISSUE THREAD

**Issue by jagomf** [nateshmbhat/touchable#42]
I have a `CanvasTouchDetector` with a `CustomPainter` and I want it to be zoomed, panned, etc. so I have put it inside a Flutter's `InteractiveViewer`.

The touchable features (I'm using `onTapDown`) work fine, but you cannot pinch inside the `CustomPainter` in order to zoom or pan the picture.

**How would you arrange the `CanvasTouchDetector` inside the `InteractiveViewer` in order for these features to keep working?**

Regarding the evolution of `touchable`, I believe the `TouchyCanvas` would need to detect zoom/pan gestures and bubble them up?

**Comment by oleksii-pimenov** [comment]
Also facing this issue

**Comment by jagomf** [comment]
Just noticed this might be very similar to #18
