### ISSUE TITLE
Pass an object to touchableCanvas to retrieve from TapDownDetails on tap

### ISSUE THREAD

**Issue by markfili** [nateshmbhat/touchable#5]
Hi, thank you for this awesome package.
I was wondering if it was possible to pass an object to the canvas that would be collected after tap down? 

Something like:
```
touchableCanvas.drawOval(Rect...., Paint..., customIndexOrObject, onTapDown: (tapDetails) {
    print(tapDetails.customIndexOrObject);
});
```

where the customIndexOrObject would be something like a tag; an integer to identify the drawing on the canvas that was clicked on or some small object to retrieve and act upon.

**Comment by nateshmbhat** [comment]
You can achieve the same use case by using the variable outside of the scope of the function or within the function however you see fit.

```
var object = MyClass();

touchableCanvas.drawOval(Rect...., Paint..., onTapDown: (tapDetails) {
    print(object);
});
```

I don't find adding a field to pass a custom object to the canvas explicitly would be a neat thing 🤔
