### ISSUE TITLE
Hello, i interest in this repo.

### ISSUE THREAD

**Issue by xrr2016** [nateshmbhat/touchable#7]
I  watch the source code, and don't understand the role of ShapeHandler, can you explain what it does, and how it work? Thank you.

https://github.com/nateshmbhat/touchable/blob/3e7a860c91541eaa729747e5e8084b2dc24eec74/lib/src/shape_handler.dart#L9

**Comment by nateshmbhat** [comment]
Shape handlers has a stack which keeps getting filled as more shapes are drawn on the screen. when ever a gesture event triggers , it takes the top most shape in the stack and gives the callback to that shape.
